# Generated by Django 4.0.3 on 2022-03-23 19:49

import app_projects.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(default=main.utilities.simple_uuid, editable=False, max_length=36)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=600)),
                ('type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], default=('residential', 'Residential'), max_length=20)),
                ('building_area', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Building area')),
                ('cubic_capacity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Cubic capacity')),
                ('height', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('image_thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to=app_projects.models.ProjectModel.thumbnail_image, verbose_name='Thumbnail image')),
                ('author', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
