# Generated by Django 4.0.3 on 2022-03-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pending_validation',
            field=models.BooleanField(default=False),
        ),
    ]
