# Generated by Django 4.0.3 on 2022-03-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_customuser_pending_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
