# Generated by Django 4.0.3 on 2022-03-19 16:43

import app_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_customuser_is_activated_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_cover',
            field=models.ImageField(blank=True, default='default_cover_picture.jpg', max_length=255, null=True, upload_to=app_users.models.CustomUser.profile_picture),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image_profile',
            field=models.ImageField(blank=True, default='default_profile_picture.jpg', max_length=255, null=True, upload_to=app_users.models.CustomUser.cover_photo),
        ),
    ]
